<?php

return [
    'PERMISSION_BITMASK_AGENTS' => 1,
    'PERMISSION_BITMASK_AGENT_STATUSES' => 2,
    'PERMISSION_BITMASK_TICKET_STATUSES' => 4,
    'PERMISSION_BITMASK_VIEW_MESSAGES' => 8,
    'PERMISSION_BITMASK_AFFILIATES' => 16,
    'PERMISSION_BITMASK_TO_DO_CHECKLISTS' => 32,
    'PERMISSION_BITMASK_TICKET_STATUS_DEPENDENCIES' => 64,
    'PERMISSION_BITMASK_DOC_UPLOAD_TYPES' => 128,
    'PERMISSION_BITMASK_VIEW_NOTIFICATIONS' => 256,
    'PERMISSION_BITMASK_MANAGE_ALERT_MESSAGES' => 512,
];
